#!/bin/bash

ARGC=("$#")
ARGV=("$@")

SEARCH=()
TAGS=()
OPEN=0
SEARCH_PATTERN=0
SEARCH_TAG=0

function display_usage {
  echo "usage: obs-search <options>"
  echo "<options>"
  echo "-e|--pattern <patterns>   search vault for patten"
  echo "-t|--tag     <tags>       search vault for tag"
  echo "-o|--open                 open all pdfs that match (system default application)"
  exit 1;
}

function check {
	if [ -d "./.obsidian" ]; then
    return 0
  else
  	echo "Warning: searching folder without an obsidian vault detected"
  	read -p "continue search?(Y/n):  " answer
  	case ${answer:0:1} in
    	y|Y )
        return 0
    	;;
    	* )
        exit 1
    	;;
		esac
	fi
}


function process_cl {
	E=0
	T=0
	for ((i=0; i<$ARGC; i++))
	do
		INPUT=${ARGV[i]}
  	case $INPUT in
    	-o|--open)
				OPEN=1
      	;;
      -e|--pattern)
				E=1
				T=0
				;;
			-t|--tag)
				E=0
				T=1
				;;
    	-*|--*)
      	echo "Error: Unknown option $INPUT"
      	display_usage
      	;;
    	*)
				if [ $E -eq 1 ]; then
					SEARCH+=("$INPUT")
					SEARCH_PATTERN=1
				elif [ $T -eq 1 ]; then 
					TAGS+=("$INPUT")
					SEARCH_TAG=1
				fi;
      	;;
  	esac
	done

	if [ "$SEARCH_PATTERN" -eq 0 ] && [ "$SEARCH_TAG" -eq 0 ]; then
  	echo "Error: no inputs for search entered"
  	display_usage
  fi;
}

function main {


	for (( i=0; i<${#SEARCH[@]}; i++ ));
	do
		if [ $i -eq 0 ]; then
			QUERY="${SEARCH[$i]}"
		else
			QUERY="$QUERY|${SEARCH[$i]}"
		fi
	done

	for (( i=0; i<${#TAGS[@]}; i++ ));
	do
		if [ $i -eq 0 ]; then
			REFINEMENT="#${TAGS[$i]}"
		else
			REFINEMENT="$REFINEMENT|#${TAGS[$i]}"
		fi
	done


	if [ "$SEARCH_PATTERN" -eq 1 ]; then

		echo ""
		FOUND=($(pdfgrep -lr . -e "$QUERY"))
		for (( i=0; i<${#FOUND[@]}; i++ ));
		do
			if [ $SEARCH_TAG -eq 1 ]; then
				FILE=$( find $(dirname ${FOUND[$i]}) -name *.md)
				if grep -q $REFINEMENT $FILE; then
	   			echo "$( dirname ${FOUND[$i]} | sed -e 's/_/ /g' | cut -c 3-)"
	   			if [ $OPEN -eq 0 ]; then
	   				xdg-open "${FOUND[$i]}" 1>/dev/null 2>&1
	   			fi;
				fi
			else 
				echo "$( dirname ${FOUND[$i]} | sed -e 's/_/ /g' | cut -c 3-)"
				if [ $OPEN -eq 1 ]; then
	   			xdg-open "${FOUND[$i]}" 1>/dev/null 2>&1
	   		fi;
			fi;
		done

	elif [ "$SEARCH_TAG" -eq 1 ]; then
		FOUND=($( find . -name *.md))
		for (( i=0; i<${#FOUND[@]}; i++ ));
			do
				if grep -q $REFINEMENT ${FOUND[$i]}; then
	    		echo "$( dirname ${FOUND[$i]} | sed -e 's/_/ /g' | cut -c 3-)"
	    		if [ $OPEN -eq 1 ]; then
	    			FILE=$( find $(dirname ${FOUND[$i]}) -name *.pdf)
	   				xdg-open "${FILE}" 1>/dev/null 2>&1
	   			fi;
	    	fi
			done
	fi;
}	

check
process_cl
main
exit 0;