#!/bin/bash

ARGC=("$#")
ARGV=("$@")

FILE=""
TITLE=""
LINKS=()
TAGS=()

T=0
L=0

function display_usage {
  echo "usage: obs-paper <pdf> <title> <options>"
  echo "<options>"
  echo "-l|--link <link file(s)> (no ext)	insert graph link to selected file"
  echo "-t|--tag <tag(s)>									insert tag"
  exit 1;
}

function check {
	if [ -d "./.obsidian" ]; then
    return 0
  else
  	echo "Warning: building folder without an obsidian vault detected"
  	read -p "continue building the folders?(Y/n):  " answer
  	case ${answer:0:1} in
    	y|Y )
        return 0
    	;;
    	* )
        exit 1
    	;;
		esac
	fi
}

function process_cl {
	for ((i=0; i<$ARGC; i++))
	do
		INPUT=${ARGV[i]}
  	case $INPUT in
    	-l|--link)
				L=1
				T=0
      	;;
      -t|--tag)
				L=0
				T=1
				;;
    	-*|--*)
      	echo "Error:  unknown option $INPUT"
      	display_usage
      	;;
    	*)
      	if [ $i -eq 0 ]; then
      		FILE=$INPUT
      		if [ -f "$FILE" ]; then
    				echo "Status: running on $FILE"
  				else
  					echo "Error:  file could not be read - $FILE"
  					display_usage
					fi
      	elif [ $i -eq 1 ]; then
      		TITLE=$INPUT
      	else
      		if [ $L -eq 1 ]; then
      			LINKS+=("$INPUT")
      		elif [ $T -eq 1 ]; then 
      			TAGS+=("$INPUT")
      		fi;
      	fi
      	;;
  	esac
	done

}

function main {
	process_cl
	check

	if [ -z "$TITLE" ]
	then
      echo "Error:  title input is empty"
      display_usage
	else
			echo "Status: building $TITLE directory"
      mkdir -p $TITLE
	fi

	NEWFILE="$TITLE/$TITLE.md"
	echo "Status: building markdown file"
	touch $NEWFILE

	echo "---" >> $NEWFILE
	echo "title: ${TITLE//[_]/ }" >> $NEWFILE
	echo "---" >> $NEWFILE


  for (( i=0; i<${#TAGS[@]}; i++ ));
  do
  	echo "#${TAGS[$i]}" >> $NEWFILE
	done
	echo "#new" >> $NEWFILE
	echo "" >> $NEWFILE

	BASE="$(basename $FILE)"
	echo "[open paper](./$BASE)" >> $NEWFILE
	echo "" >> $NEWFILE

	echo "## Links" >> $NEWFILE
	echo "---" >> $NEWFILE

	for (( i=0; i<${#LINKS[@]}; i++ ));
  do
  	echo "#${LINKS[$i]}" >> $NEWFILE
	done
	echo "" >> $NEWFILE

	echo "## BibTex" >> $NEWFILE
	echo "---" >> $NEWFILE
	echo "\`\`\`" >> $NEWFILE
	pdf2bib $FILE >> $NEWFILE
	echo "\`\`\`" >> $NEWFILE
	echo "" >> $NEWFILE
	
	mv $FILE $TITLE
}


main

exit 0;